source: "/Users/poojashetty/Documents/MasterThesis/Dataset/Cityscapes"
dataset_name: "Dataset100_Cityscapes20" # or "Dataset101_Cityscapes50"
train_rel_path: "leftImg8bit_trainvaltest/leftImg8bit/train"
val_rel_path: "leftImg8bit_trainvaltest/leftImg8bit/val"
test_rel_path: "leftImg8bit_trainvaltest/leftImg8bit/test"
label_rel_path: "gtFine_trainvaltest/gtFine"
#test_rel_path: "leftImg8bit_trainvaltest_foggy/leftImg8bit_foggy/test"
train_split_ratio: 0.2

valid_classes: [26]
void_classes: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,30,31,32,33,-1]

