dataset_name: "Dataset200_MultiscannerSCC"
patch_size: 512
level: 0
patches_per_slide: 50
down_factor: 16

data_split_csv: scc_dataset.csv

defaults:
  - _self_
  - scanner:
    - p1000
  - location:
    - pc
  - nclass:
    - two_with_ignore

train_data_ratio: 1
test_only: false
actual_seg_output: null
predicted_seg_output: null